### PR TITLE
Corrected some issues with example JSONClient

### PR DESCRIPTION
**Pull request by dominikl**
Correct some issues in JSONClient example remarked in https://github.com/openmicroscopy/ome-documentation/pull/1627

### CODE REVIEW

**Comment by will-moore** [comment]
@mtbc @jburel Happy with these changes before I merge them?

**Comment by dominikl** [comment]
@mtbc, I removed the various `args[i].trim()` again, as the `trim()`s actually aren't necessary.

**Comment by mtbc** [comment]
The changes related to my comments are fine.

**Comment by jburel** [comment]
@will-moore merge it

**Pull request merged**
